### ISSUE TITLE
Only works for half of the map (1.17.1)

### ISSUE THREAD

**Issue by StickyBoy321** [MorganAnkan/MCScreenshare#7]
![Screenshot 2022-01-09 151858](https://user-images.githubusercontent.com/89932458/148688584-2496d130-4c07-4ee7-b6f0-2368ce3a1b92.png)

**Comment by MorganAnkan** [comment]
as i remember it should be like that as else, if you only use 1 map it will look weird due to resizing and stuff, but i should implement so you can have multiple maps aka a bigger screen but i havent been bothered to do that yet

**Comment by StickyBoy321** [comment]
Ok, thank you. can't wait to see how it turns out if you get round to doing it
